name: Test en DigitalOcean
on: [push]
jobs:
  create_droplets_vpc:
    name: Create Droplet in DigitalOcean
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      
      - name: Craete VPC
        run: doctl vpcs create --name vpc1-tests --region nyc1 --ip-range 192.168.10.0/24
      
      - name: Get VPC info
        run: doctl vpcs list --format ID,Name | grep vpc1 > temp.txt

      - name: Get VPC ID
        run: awk '{print $1; exit}' temp.txt > tempid.txt

      - name: Create a single droplet and assign it to VPC
        run: doctl compute droplet create droplet1tests --image centos-7-x64 --size s-1vcpu-1gb --region nyc1 --user-data-file script.sh --vpc-uuid "$(cat tempid.txt)"